### ISSUE TITLE
blogdown default site only renders with relativeURLs & uglyURLs options set

### ISSUE THREAD

**Issue by ras44** [rstudio/blogdown#372] opened 2019-03-08 10:19 UTC
reprex:

Create a new site either with `blogdown::new_site() or File->New Project->New Directory->R Blogdown site.

The site framework is created, but in preview the links to articles don't work and css is missing.

I found a solution [here](https://stackoverflow.com/questions/54972527/bad-rendering-of-the-local-index-html-from-public-folder-using-hugo) which mentions adding to config.toml:

```
relativeURLs = true
uglyURLs = true
```

`relativeURLs = true` allows it to find the CSS and render the page properly.
`uglyURLs=true` allows the links to articles to work.

I'm not sure if this is the proper solution for what is going on though.  Thanks.

**Comment by yihui** [comment] 2019-03-08 17:29
Please carefully describe the steps to reproduce your issue. In particular, this is too brief:

> in preview the links to articles don't work and css is missing

How exactly did you get the preview?

If you haven't, please read at least Chapter 1 of the blogdown book. If you are really busy, read Section 1.7: https://bookdown.org/yihui/blogdown/workflow.html

If the default site is broken, I guess we should have received many reports about it, but you seem to be the first one (over the two years).

**Comment by ras44** [comment] 2019-03-11 12:32
Thanks.  I have read Chapter 1 of the book and attempted this a few times before going to the stackoverflow solution that I mentioned.  To provide more detail:

- I am using a CentOS7 linux cloud instance with R 3.5.0 and RStudio Server 1.1.453 installed; note RStudio Server serves on port 8787, so the IDE is available on <INSTANCE_IP>:8787
- install blogdown, hugo
- Create a new site either with `blogdown::new_site() or File->New Project->New Directory->R Blogdown site.
- The site framework is created (files are all in the right place), but the preview doesn't seem to show the correct links to sample articles

By preview, I mean either the preview that shows in the RStudio Server viewer tab or the window that opens up when running serve_site.

I'm not sure, but maybe this was an issue because I'm running on RStudio Server on a linux instance?

Please note that that stackoverflow question was posted just 7 days ago and mentions blogdown specifically, so it does appear at least one other person has run into this issue.

**Comment by yihui** [comment] 2019-03-11 14:19
Duplicate of #124

**Closed by yihui** 2019-03-11 14:19 UTC

**Comment by yihui** [comment] 2019-03-12 14:13
FYI the new version of **blogdown** has been released to CRAN (which should solve your problem). Thanks for the report!

**Comment by ras44** [comment] 2019-03-12 14:32
Phenomenal.  Thank you for the fast turnaround!
