### ISSUE TITLE
blogdown:::serve_site() keeps opening new browser tabs

### ISSUE THREAD

**Issue by jennybc** [rstudio/blogdown#404] opened 2019-08-20 16:20 UTC
When I write a new post for https://www.tidyverse.org, I generally use the "Serve Site" add-in, which calls `blogdown:::serve_site()`. It initially appears in RStudio's Viewer and I use "Show in New Window" to send it over to Safari. There, I navigate down to the post I'm working on. So far so good.

As I make edits and save, over in the `.Rmarkdown` file corresponding to the post, somehow the way I'm constantly rendering and previewing frequently (but not always?) results in a new tab being opened. It feels like it's because my existing Safari tab is not viewing the main page, but is viewing a specific post. That is just a theory. But it swiftly results in a crazy proliferation of browser tabs, conceivably one per "save".

**Comment by yihui** [comment] 2019-08-20 21:29
I see a few **blogdown** options in https://github.com/tidyverse/tidyverse.org/blob/master/.Rprofile, and I wonder if you have set any options in your own `~/.Rprofile`.

Does the same problem occur in other browsers? Does it occur if you serve the site after setting 

```r
options(
  blogdown.generator.server = TRUE,
  blogdown.hugo.server = c('-D', '-F', '--navigateToChanged')
)
```

?

All packages up-to-date?

**Comment by jennybc** [comment] 2019-08-21 02:17
Ooh interesting. I was not even aware of a project-specific `.Rprofile` for that project/repo/site!

There is nothing in my user-level `.Rprofile` that is conceivably related to this. I realize that's presumptuous, but I genuinely am pretty sure about that.

I'm heading off for vacation but will try these new options (and ensure the stack is up-to-date) upon my return, when I work in blowdown.

**Comment by yihui** [comment] 2019-08-21 03:19
Okay. Sounds good.

**Comment by yihui** [comment] 2019-08-23 15:48
One possible reason is that you clicked the `Knit` button once in the **blogdown** project and the RStudio Viewer displayed the HTML output page. When there is a page in the viewer history, `blogdown::serve_site()` may open the site in an external browser. I don't know why. This could be an IDE bug. My solution is to clear the viewer history (using the broom button), and call `servr::browse_last()` to bring back the website to the viewer.

**Comment by daczarne** [comment] 2020-03-17 02:34
I have the same issue working on Windows 10 and Chrome (don't really mind it, just sharing in case you wanted to know if it was a specific Mac + Safari thing).

A follow up on your .Rprofile comment. I don't have one on my blogdown repo, did you guys tested whether setting those options solves it?

**Comment by yihui** [comment] 2020-03-17 13:49
@daczarne I haven't heard back from @jennybc, but would you provide your `xfun::session_info('blogdown')`? In particular, I wonder which version of RStudio you are using (if you use it at all).

**Comment by daczarne** [comment] 2020-03-18 01:47
always RStudio lol

```
> xfun::session_info('blogdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.2.1335

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_0.18   bookdown_0.18   digest_0.6.25   evaluate_0.14   glue_1.3.2      graphics_3.6.3 
  grDevices_3.6.3 highr_0.8       htmltools_0.4.0 httpuv_1.5.2    jsonlite_1.6.1  knitr_1.28      later_1.0.0     magrittr_1.5   
  markdown_1.1    methods_3.6.3   mime_0.9        promises_1.1.0  R6_2.4.1        Rcpp_1.0.3      rlang_0.4.5     rmarkdown_2.1  
  servr_0.16      stats_3.6.3     stringi_1.4.6   stringr_1.4.0   tinytex_0.20    tools_3.6.3     utils_3.6.3     xfun_0.12      
  yaml_2.2.1     
```

```
> RStudio.Version()$version
[1] ‘1.2.1335’
```

**Comment by yihui** [comment] 2020-03-18 20:22
Could you try the RStudio preview version? https://rstudio.com/products/rstudio/download/preview/

**Comment by daczarne** [comment] 2020-03-21 03:20
Done! It seems to solve the problem. I tried every instance I had spotted the issue. Can't get to do it now. I'll let you know if it happens again, but so far so good. Thanks!

```
> xfun::session_info('blogdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.3.923

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_0.18   bookdown_0.18   digest_0.6.25   evaluate_0.14   glue_1.3.2      graphics_3.6.3  grDevices_3.6.3
  highr_0.8       htmltools_0.4.0 httpuv_1.5.2    jsonlite_1.6.1  knitr_1.28      later_1.0.0     magrittr_1.5    markdown_1.1    methods_3.6.3  
  mime_0.9        promises_1.1.0  R6_2.4.1        Rcpp_1.0.3      rlang_0.4.5     rmarkdown_2.1   servr_0.16      stats_3.6.3     stringi_1.4.6  
  stringr_1.4.0   tinytex_0.20    tools_3.6.3     utils_3.6.3     xfun_0.12       yaml_2.2.1     
```

**Comment by yihui** [comment] 2020-03-21 04:01
Sounds good. I'll close this issue for now, but can reopen it if the problem occurs again. Thank you!

**Comment by denizCvrl** [comment] 2020-04-25 06:00
I have the same problem after updating to Windows 10 and I am using the preview version. Any other suggestion?

```
> RStudio.Version()$version
[1] ‘1.3.947’
> xfun::session_info('blogdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Locale:
  LC_COLLATE=English_United States.1252 
  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_0.18   bookdown_0.18  
  digest_0.6.25   evaluate_0.14   glue_1.4.0      graphics_3.6.3 
  grDevices_3.6.3 highr_0.8       htmltools_0.4.0 httpuv_1.5.2   
  jsonlite_1.6.1  knitr_1.28      later_1.0.0     magrittr_1.5   
  markdown_1.1    methods_3.6.3   mime_0.9        promises_1.1.0 
  R6_2.4.1        Rcpp_1.0.4.6    rlang_0.4.5     rmarkdown_2.1  
  servr_0.16      stats_3.6.3     stringi_1.4.6   stringr_1.4.0  
  tinytex_0.22    tools_3.6.3     utils_3.6.3     xfun_0.13      
  yaml_2.2.1     
```

**Comment by daczarne** [comment] 2020-05-07 03:27
I've noticed a pattern. If I add/delete/move a file (for example an image) inside de themes/hugo-tranquilpeak-theme sub dir it works ok. But if I do it in the root directory (where my .rproj is) then it opens a new window. Maybe it helps to isolate the issue.

(BTW: I went back to RStudio 1.2.5042 since I last posted because the preview version had some bugs with other things)

```
> xfun::session_info('blogdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.2.5042

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 BH_1.72.0.3     blogdown_0.18   bookdown_0.18   digest_0.6.25   evaluate_0.14   glue_1.4.0      graphics_3.6.3 
  grDevices_3.6.3 highr_0.8       htmltools_0.4.0 httpuv_1.5.2    jsonlite_1.6.1  knitr_1.28      later_1.0.0     magrittr_1.5   
  markdown_1.1    methods_3.6.3   mime_0.9        promises_1.1.0  R6_2.4.1        Rcpp_1.0.4.6    rlang_0.4.5     rmarkdown_2.1  
  servr_0.16      stats_3.6.3     stringi_1.4.6   stringr_1.4.0   tinytex_0.22    tools_3.6.3     utils_3.6.3     xfun_0.13      
  yaml_2.2.1 
```

**Comment by yihui** [comment] 2020-05-23 21:01
I'm reopening this issue since there are still more people having the same issue:

- @lopierra https://lopierra.rbind.io/post/i_made_a_website/
- @Shelmith-Kariuki https://twitter.com/Shel_Kariuki/status/1263950317365821441

Unfortunately I have tried several times but never been able to reproduce the problem. I have tried combinations of Windows, macOS, different versions of RStudio, Google Chrome, IE, and Safari. I have also tried to move files to/from the root directory according to @daczarne's tip. I just couldn't reproduce it. The only thing I haven't tried is Windows 10, which I currently don't have access to, but @jennybc experienced the issue on macOS, so it doesn't seem to be an issue specific to Windows...

**Comment by denizCvrl** [comment] 2020-05-24 00:55
I set the suggested options of #404 in my .Rprofile. It didn't work in my case. I hadn't had this problem up until I updated to windows 10 so I assumed it was related to that.

But I remember another pattern before updating Windows 10  that I mentioned in a tutorial about making a website (https://makingwebsiteswithr.rbind.io/tutorial/02-quick-start/). When I ran serve_site() function for the second time without restarting the session, the website automatically opened in my browser. It started to show my changes only in the browser version. I ran it a third time, fourth time…without restarting. Occasionally, I was able to see changes both in my browser and in the viewer, but other times only in the browser. I am sure there is some kind of logic for this behavior but I couldn’t figure out at the time. Maybe the cause is the same so I wanted to mention it here. I didn't think that it was a bug because normally I was supposed to restart the session.

**Comment by yihui** [comment] 2020-05-24 04:25
@denizCvrl Thank you soooo much! By running `blogdown::serve_site()` multiple times, I was finally able to reproduce the issue on Windows (with the latest RStudio v1.3.959)!

Before I figure out a fix (I guess this might be an issue of the RStudio IDE), I think you should avoid running `serve_site()` multiple times (or equivalently, clicking the RStudio addin "Serve Site" multiple times). It doesn't really make much sense to serve the same site multiple times. It suffices to do it only once per R session, as mentioned in the **blogdown** book: https://bookdown.org/yihui/blogdown/workflow.html

**Comment by denizCvrl** [comment] 2020-05-24 04:38
Great, i am so happy that it helped you figure out the problem. Looking forward to your solution. 
Yes, i know now that i don't have to run multiple times. That was when I was learning it for the first time last year.

**Comment by lopierra** [comment] 2020-05-24 05:15
I was just about to write the same thing! I was trying to figure out how to recreate the problem, and I realized it also happened when I clicked on "Serve Site" in the Addins menu more than once per session. It also happened when I was learning blogdown for the first time! I guess I need to update my blog post :)

I am using RStudio 1.2.1335 with Windows 10 & Chrome. Your previous advice ("My solution is to clear the viewer history (using the broom button), and call `servr::browse_last()` to bring back the website to the viewer.") worked for me.

**Closed** 2020-05-26 19:17 UTC

**Comment by yihui** [comment] 2020-05-26 19:21
I just submitted a fix to prevent users from running `blogdown::serve_site()` multiple times for the same site in the same R session, because this is rarely necessary.

You may test the development version via

```r
remotes::install_github('rstudio/blogdown')
```

This should at least fix the symptom, but the root cause is still a mystery to me (might be related to https://github.com/rstudio/rstudio/issues/3577).

Thanks!

**Comment by lopierra** [comment] 2020-05-26 19:26
Thank you for being so on top of tracking and fixing bugs - that is amazing!

**Comment by yihui** [comment] 2020-05-26 19:33
You are welcome! This issue just happens to have puzzled me for too long, have affected multiple users, and more importantly, have finally become reproducible to me (with your helpful tips).

**Comment by lopierra** [comment] 2020-05-28 15:21
It works!!

I confirmed that with the CRAN version, running `serve_site()` more than once per session opens browser tabs. After installing the dev version, I get the helpful warning message and no browser tabs! 

Just wanted to point out a typo in case you want to fix it:
"If you do want to start~~ing~~ a new server..."

Thanks again!

**Comment by yihui** [comment] 2020-05-28 15:36
> Just wanted to point out a typo in case you want to fix it:
> "If you do want to start~ing~ a new server..."

@lopierra Oops :) Thanks! I just fixed the typo (originally I wrote "if you do prefer starting a new server", then changed "prefer" to "want to", and forgot to change "starting" accordingly).

**Comment by denizCvrl** [comment] 2020-06-07 03:18
@yihui  thank you so much for the fix about running serve_site multiple times. I just had a chance to look at it. It works perfectly.  However, my main problem was not that. When I ran blogdown::serve_site(), it opened a browser directly instead of showing on the viewer even though I ran it just once. I hadn't had that problem until I updated to Windows 10. Anyways, I was looking for a solution online from other posts.  I followed your suggestion in this [post](https://stackoverflow.com/questions/52312957/how-to-access-a-rstudio-blogdown-website-on-local-network) and `devtools::install_github('yihui/servr')` solved the problem. I have no idea why it worked :) but I just wanted to write here in case it helps anybody else with the same problem.

**Comment by Robinlovelace** [comment] 2022-12-30 22:26
This is a really weird issue. It hit me today and I've attempted various remedies outlined here but to no avail. This is what I see, ~5th time it's happened and it's never happened to me before after years of using blogdown, I'm bamboozled.

![image](https://user-images.githubusercontent.com/1825120/210115584-f47a1e9b-2e04-4eea-91b2-eb313295df86.png)

See https://github.com/rbind/robinlovelace for info, nothing too unusual in there. Could it be the combination of RStudio, Wowchemy and embedded tweets?

**Comment by yihui** [comment] 2022-12-30 23:03
@Robinlovelace I'm pretty sure this is an RStudio problem (due to the switch to Electron): https://github.com/rstudio/rstudio/issues/12494 Feel free to chime in/upvote there.
