### ISSUE TITLE
New post rendering TOML instead of YAML for cocoa-enhanced-theme

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#301] opened 2018-06-11 02:54 UTC
Hi,

I asked this on community.rstudio.com awhile ago and other folks could replicate the issue, but no answers. I'm using this theme for teaching this quarter, and all my students are also seeing the same issue, so it appears across operating systems and set ups, but I have only had this issue with the cocoa enhanced theme (https://github.com/mtn/cocoa-eh-hugo-theme).

My issue is that when I try to create a new R Markdown post, the front matter is in TOML markup instead of YAML. This happens whether I use the New Post Add in or the `new_post()` function.

<img width="800" alt="screen shot 2018-06-10 at 7 50 03 pm" src="https://user-images.githubusercontent.com/12160301/41210577-815b6bba-6ce7-11e8-9932-9e939cf9853c.png">

The .Rmd sample post from the example site generates just fine (https://raw.githubusercontent.com/apreshill/ada-blog/master/content/blog/2015-07-23-r-rmarkdown.Rmd).

I'm filing an issue here because the [default.md file](https://raw.githubusercontent.com/mtn/cocoa-eh-hugo-theme/master/archetypes/default.md) in the theme looks as it should (as far as I can tell, but if you see otherwise I apologize for placing the issue here!), so I'm wondering if it is a `blogdown` issue that perhaps others have seen with this or other themes.

My set-up:

- R version 3.4.1 (I cannot upgrade past that b/c I am using a work computer and they won't let us upgrade our Mac operating systems). 
- Github version of blogdown just updated again tonight.
- Local `hugo` version is 0.41

If it helps, here is my repo for the site I'm trying to build: https://github.com/apreshill/ada-blog

Thank you in advance!

**Comment by yihui** [comment] 2018-06-11 04:14
Looks like a regression bug of Hugo. I'm sure it worked sometime last year. I have this internal function to convert TOML to YAML:
https://github.com/rstudio/blogdown/blob/ad8be3ffb5ec8576a008375d8da6ec76ab01a902/R/hugo.R#L228-L241

I need to investigate what exactly changed in Hugo.

**Comment by yihui** [comment] 2018-06-11 04:41
Should be fixed on blogdown's side now, although I still guess it is a Hugo issue. Thanks for the report!

**Closed** 2018-06-11 04:40 UTC
Labels: bug

**Comment by apreshill** [comment] 2018-06-11 14:12
Thank you @yihui- that worked perfectly!
