### ISSUE TITLE
Rmd files have not the same stlye than md files on webspace

### ISSUE THREAD

**Issue by ogansser** [rstudio/blogdown#610] opened 2021-04-09 14:49 UTC
Hi, 

I try several themes, It is always the same. Md files work, Rmd files do not work. It seems that there is something wrong with the HTML head. 

I use the actual RStudio, R, and blogdown 1.2. If I go back to blogdown 0.2 it works.

**Comment by yihui** [comment] 2021-04-09 15:33
This might be a duplicate of #608.

Please see https://github.com/rstudio/blogdown/issues/608#issuecomment-816758671.

**Comment by ogansser** [comment] 2021-04-09 15:57
look at this: http://gansser.info/post/2020-12-01-r-rmarkdown/

compared to this:

http://gansser.info/post/basic-elements/


Am Fr., 9. Apr. 2021 um 17:33 Uhr schrieb Yihui Xie <
***@***.***>:

**Comment by yihui** [comment] 2021-04-09 16:06
When you open an issue here, you are [presented with a checklist](https://github.com/rstudio/blogdown/blob/master/.github/ISSUE_TEMPLATE/bug-report.md), which you deleted in the issue ([again](https://github.com/rstudio/blogdown/issues/608#issuecomment-815284839)).

One checkbox asked that you run `blogdown::check_site()`. Did you do that? If you did, did you follow its instructions?

**Comment by ogansser** [comment] 2021-04-12 11:24
Check_site was OK. I transferred the public folder to my webspace. All Rmd
files do not work. Please see www.gansser.info. I took the original Binario
theme. Did not change anything. Same with other themes. With blogdown 0.20
everything works well.

> blogdown::check_site()
― Running a series of automated checks for your blogdown website project...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
○ A successful check looks like this.
● [TODO] A check that needs your attention looks like this.
| Let's check out your blogdown site!
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
― Checking config.yaml
| Checking "baseURL" setting for Hugo...
● [TODO] Set "baseURL" to "/" if you do not yet have a domain.
| Checking "ignoreFiles" setting for Hugo...
● [TODO] Set "ignoreFiles" to ["\\.Rmd$", "\\.Rmarkdown$", "_cache$",
"\\.knit\\.md$", "\\.utf8\\.md$"]
| Checking setting for Hugo's Markdown renderer...
| You are using the Markdown renderer 'goldmark'.
● [TODO] Allow goldmark to render raw HTML by adding this setting to
config.yaml (see https://github.com/rstudio/blogdown/issues/447 for more
info):

markup:
  goldmark:
    renderer:
      unsafe: true

> Do you want blogdown to set this for you? (y/n) y
― Check complete: config.yaml

― Checking .gitignore
● [TODO] .gitignore was not found. You may want to add this.
― Checking Hugo
| Checking Hugo version...
○ Found 3 versions of Hugo. You are using Hugo 0.82.0.
| Checking .Rprofile for Hugo version used by blogdown...
○ blogdown is using Hugo 0.82.0 to build site locally.
― Check complete: Hugo

― Checking netlify.toml...
○ Found HUGO_VERSION = 0.82.0 in [build] context of netlify.toml.
| Checking that Netlify & local Hugo versions match...
○ It's a match! Blogdown and Netlify are using the same Hugo version
(0.82.0).
| Checking that Netlify & local Hugo publish directories match...
○ Good to go - blogdown and Netlify are using the same publish directory:
public
― Check complete: netlify.toml

― Checking content files
| Checking for validity of YAML metadata in posts...
○ All YAML metadata appears to be syntactically valid.
| Checking for previewed content that will not be published...
○ Found 0 files with future publish dates.
○ Found 0 files marked as drafts.
| Checking your R Markdown content...
○ All R Markdown files have been knitted.
○ All R Markdown output files are up to date with their source files.
| Checking for .html/.md files to clean up...
○ Found 0 duplicate .html output files.
○ Found 0 incompatible .html files to clean up.
| Checking for the unnecessary 'content/' directory in theme...
○ Great! Your theme does not contain the content/ directory.
― Check complete: Content


Am Fr., 9. Apr. 2021 um 18:06 Uhr schrieb Yihui Xie <
***@***.***>:

**Comment by ogansser** [comment] 2021-04-12 11:34
Problem solved. With Rmd files you need the additionals code:

https://github.com/J-Siu/hugo-theme-sk3/issues/28#issuecomment-816810141

Am Mo., 12. Apr. 2021 um 13:23 Uhr schrieb Oliver Gansser ***@***.***

**Closed** 2021-04-12 21:43 UTC
Labels: bug, reprex

**Comment by yihui** [comment] 2021-04-12 21:46
`check_site()` suggested above:

> ● [TODO] Set "ignoreFiles" to `["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]`

You need to do that.

Since you didn't provide a reproducible example, I did my best-effort guess on what happened in this case. You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Restart R, run `blogdown::check_site()`, and I guess it should tell you what to do in case you run into problems again. Thanks!

**Comment by frank0434** [comment] 2021-11-03 11:06
Had similar issues and followed `blogdown::check_site()` to-do list.  Problem solved.
