### ISSUE TITLE
error calling getenv: access denied

### ISSUE THREAD

**Issue by gergiu** [rstudio/blogdown#673] opened 2021-12-18 07:09 UTC
Hi, I hope someone can help me with this issue:

```
Launching the server via the command:
  C:/Users/w0rk5/AppData/Roaming/Hugo/0.91.0/hugo.exe server --bind XXX.X.X.X -p YYYY --themesDir themes -t hugo-lithium -D -F --navigateToChanged
Error: Error building site: "C:\_DATI\MEGAdrive\Class\myWebSite\gergiu.github.io\content\post\2020-12-01-r-rmarkdown\index.html:9:14": failed to render shortcode "blogdown/postref": failed to process shortcode: "C:\_DATI\MEGAdrive\Class\myWebSite\gergiu.github.io\layouts\shortcodes\blogdown\postref.html:1:10": execute of template failed: template: shortcodes/blogdown/postref.html:1:10: executing "shortcodes/blogdown/postref.html" at <getenv "BLOGDOWN_POST_RELREF">: error calling getenv: access denied: "BLOGDOWN_POST_RELREF" is not whitelisted in policy "security.funcs.getenv"; the current security configuration is:

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
```

It seems i can't use getenv.

Thank you.

**Comment by yihui** [comment] 2021-12-19 00:26
Duplicate of #672.

**Closed by yihui** 2021-12-19 00:26 UTC

**Comment by yihui** [comment] 2021-12-19 04:00
Should be fixed now. Thanks for the report! You can install the development version via

```r
remotes::install_github('rstudio/blogdown')
```

**Comment by gergiu** [comment] 2021-12-19 07:35
Thanks for your help!
