### ISSUE TITLE
plot link breaks when `.Rmd` post filename contains Chinese

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/blogdown#233] opened 2017-11-26 16:26 UTC
Here is a [reproducible example](https://github.com/dongzhuoer/blogdown-issue)

I create it from RStudio's template and add four files:

| filename | Chinese | type         |
| -------- | ------- | ------------ |
| plot     | no      | `.Rmarkdown` |
| chart    | no      | `.Rmd`       |
| 图       | yes     | `.Rmarkdown` |
| 画       | yes     | `.Rmd`       |

The above four posts all contains the same code, which draws a plot. But only the last post fails to show the plot in its output.

**Comment by yihui** [comment] 2017-11-27 04:54
Thanks for the report, but I'd say this is by design. Multibyte characters in filenames won't be supported (#83). Sorry.

**Comment by dongzhuoer** [comment] 2017-11-27 05:47
I use Ubuntu. And actually I create all these four posts using your addin.

**Comment by dongzhuoer** [comment] 2017-11-27 05:53
in the `content/post` folder. 

`chart.html` contains 
```html
<p><img src="/post/2017-11-26-chart_files/figure-html/pie-1.png" width="672" /></p>
```

but `画.html` contains 
```
<p><img src="2017-11-26-%E7%94%BB_files/figure-html/pie-1.png" width="672" /></p>
```

**Comment by yihui** [comment] 2017-11-27 15:10
It does not matter which OS you use. Multibyte characters are not supported in post filenames when the posts contain graphics output. I know what the problem is, but I don't have time to fix it.

**Comment by dongzhuoer** [comment] 2017-11-27 15:48
OK, then.

Maybe you can add this point to your book to prevent others from stepping into the same pit.

**Comment by yihui** [comment] 2017-12-10 03:44
Should be fixed now. Thanks for the report!

**Comment by dongzhuoer** [comment] 2017-12-10 09:34
Thank you so much!

But I'm afraid they is still something wrong. Though `.Rmd` post works well, `.Rmarkdown` post doesn't work now. For example, the link for `图.Rmarkdown` becomes `2017-11-26-图_files/figure-html/pie-1.png`, which lacks `/post/` in the begining.

**Comment by dongzhuoer** [comment] 2017-12-10 16:21
I also make some comment for the code in #232 (I guess you use that code to tackle this issue)

**Comment by yihui** [comment] 2017-12-11 15:42
Should be fixed now. Thanks!

**Closed** 2017-12-11 15:42 UTC

**Comment by dongzhuoer** [comment] 2017-12-11 15:50
Great!
