### ISSUE TITLE
Weird issue with crashing chrome tab

### ISSUE THREAD

**Issue by jsilve24** [rstudio/blogdown#197] opened 2017-09-14 16:38 UTC
First off, thank you for this awesome package!

I had a really weird issue (fixed) but I think it may point to a bug somewhere. 

I have been running the blog http://www.statsathome.com/ for a few months without problems. I recently wrote a post http://www.statsathome.com/2017/09/14/visualizing-the-multinomial-in-the-simplex/. (github rmarkdown here: https://raw.githubusercontent.com/jsilve24/stats_at_home/master/content/post/2017-09-14-visualizing-the-multinomial-in-the-simplex.Rmd)

At first the page would render fine in the Rstudio browser and on safari but it would crash if I tried to open it in a chrome tab. Ultimately I ended up having to rewrite a few lines (not actually changing anything of note) and I eventually got it to work. 

It did not occur if Rmarkdown was compiled and that file was opened, only if it was compiled through blogdown and opened as part of my site. 

## How to replicate problem:  
* Download my github repo:  https://github.com/jsilve24/stats_at_home
* in the file content/post/2017-09-14-visualizing-the-multinomial-in-the-simplex.Rmd remove the second call `d <- setNames(as.data.frame(prob), c("v1", "v2", "v3"))` under the heading "Effect of changing $n$ (counting as a random process)" which should be on line 73. Note that this line should not be required as it is called in the block above. 
* Try to serve the site and open this page in chrome. 

I am sorry if this does not work for you, it was reproducible on my machine. Each time I try this it just loads and loads and eventually I get a message asking if I want to kill the tab. As I said, its all fixed for me, but the fix is weird and unintuitive and was very time consuming to figure out. 

## Versions
Using package Version 0.1 for blogdown (installed via CRAN)
Hugo version 0.26

Hopefully this helps squash a bug.
Justin

**Comment by yihui** [comment] 2017-09-14 22:47
Thanks for the report with detailed instructions on how to reproduce the issue. Good news is that I can reproduce this issue in Google Chrome, and bad news is I have no idea why this happens only in Chrome. I spent an hour on this and still have no clue. This issue seems to be irrelevant to R or blogdown, since it is reproducible outside of R, e.g. I tried to deploy the site to https://embalmer-milton-46174.netlify.com/2017/09/14/visualizing-the-multinomial-in-the-simplex/ and it still crashes Chrome. This probably should be reported to the Chrome team...

**Comment by jsilve24** [comment] 2017-09-14 23:08
The only reason I thought it might be blogdown or R is that simply knitting the document (outside of blowdown) led to a document that I could view in chrome whereas when I tried to render it as part of a site there was a problem. Could obviously still be chrome though...

Justin

**Comment by yihui** [comment] 2017-09-15 02:28
Knitting the document will generate a different HTML file.

Anyway, it is an issue specific to Chrome, and I don't know what to do with it on my side.

**Comment by jsilve24** [comment] 2017-09-15 02:29
Cool. I will try to figure out how to submit chrome bug report.

**Comment by yihui** [comment] 2017-10-03 16:36
Closing this issue since it is beyond my abilities and I cannot offer any help.

**Closed by yihui** 2017-10-03 16:36 UTC
