### ISSUE TITLE
Error in rendering Wowchemy's Hugo Academic theme using blogdown

### ISSUE THREAD

**Issue by jyotishkarc** [rstudio/blogdown#640] opened 2021-07-13 14:37 UTC
I was trying to make a website of my own using Wowchemy's Hugo Academic theme. I wrote the following code after installing the `blogdown` package in R.
```
new_site(theme = "wowchemy/starter-academic")
```
I am getting the following output.
```
― Creating your new site
| Installing the theme wowchemy/starter-academic from github.com
trying URL 'https://github.com/wowchemy/starter-academic/archive/master.tar.gz'
Content type 'application/x-gzip' length unknown
downloaded 7.1 MB

trying URL 'https://github.com/wowchemy/wowchemy-hugo-modules/archive/v5.3.0.tar.gz'
Content type 'application/x-gzip' length unknown
downloaded 504 KB

Error in new_content(f2, open = FALSE) : 
  Failed to create the file 'post/2020-12-01-r-rmarkdown/index.en.Rmd'.
In addition: Warning messages:
1: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\chris-montgomery-smgTvepind4-unsplash_hu3de7c38bc09fe4bb33ec1fc222105033_3160894_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\chris-montgomery-smgTvepind4-unsplash_hu3de7c38bc09fe4bb33ec1fc222105033_3160894_0x190_resize_q75_lanczos.jpg: No such file or directory
2: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\fotografierende-333oj7zFsdg-unsplash_hu3bb23653d32c408eefe8a3992b21fbd2_986191_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\fotografierende-333oj7zFsdg-unsplash_hu3bb23653d32c408eefe8a3992b21fbd2_986191_0x190_resize_q75_lanczos.jpg: No such file or directory
3: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\glenn-carstens-peters-npxXWgQ33ZQ-unsplash_hu4fbee8b709aacc4ebfd59bb0713b9f48_588975_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\glenn-carstens-peters-npxXWgQ33ZQ-unsplash_hu4fbee8b709aacc4ebfd59bb0713b9f48_588975_0x190_resize_q75_lanczos.jpg: No such file or directory
4: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\joseph-gonzalez-zcUgjyqEwe8-unsplash_hu94ef7cc5936c0328898d9575aad95082_404249_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\joseph-gonzalez-zcUgjyqEwe8-unsplash_hu94ef7cc5936c0328898d9575aad95082_404249_0x190_resize_q75_lanczos.jpg: No such file or directory
5: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\matthew-osborn-wMRIcT86SWU-unsplash-l_hu7424330660c8095403b908ab762c7d42_6675422_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\matthew-osborn-wMRIcT86SWU-unsplash-l_hu7424330660c8095403b908ab762c7d42_6675422_0x190_resize_q75_lanczos.jpg: No such file or directory
6: In file.copy(list.files(expdir, full.names = TRUE), "../", recursive = TRUE) :
  problem copying 1e7c4408647a\starter-hugo-academic-master\exampleSite\resources\_gen\images\media\albums\demo\priscilla-du-preez-K8XYGbw4Ahg-unsplash_hu9681d6bee55a5018cc404b0ddc14c7a7_1398488_0x190_resize_q75_lanczos.jpg to ..\resources\_gen\images\media\albums\demo\priscilla-du-preez-K8XYGbw4Ahg-unsplash_hu9681d6bee55a5018cc404b0ddc14c7a7_1398488_0x190_resize_q75_lanczos.jpg: No such file or directory
7: In system2(find_hugo(), ...) :
  running command '"C:/Users/JYOTISHKA/AppData/Roaming/Hugo/0.85.0/hugo.exe" new "post/2020-12-01-r-rmarkdown/index.en.md" --themesDir themes -t starter-hugo-academic' had status 65535
```
I had read some earlier discussion [here](https://github.com/rstudio/blogdown/issues/546#issue-774542269) and [here](https://github.com/rstudio/blogdown/issues/433) which show a similar problems as I'm facing. Is there a fix for this problem ?

I had tried the saame thing with ```new_site("gcushen/hugo-academic")``` and it worked.

------------------

This is to note that I have used `remotes::install_github('rstudio/blogdown')` for installing `blogdown`. The output of `xfun::session_info('blogdown')` is following :
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Locale:
  LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
  LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
  LC_TIME=English_India.1252    

Package version:
  base64enc_0.1.3   blogdown_1.3.2    bookdown_0.22     digest_0.6.27    
  evaluate_0.14     glue_1.4.2        graphics_4.1.0    grDevices_4.1.0  
  highr_0.9         htmltools_0.5.1.1 httpuv_1.6.1      jsonlite_1.7.2   
  knitr_1.33        later_1.2.0       magrittr_2.0.1    markdown_1.1     
  methods_4.1.0     mime_0.11         promises_1.2.0.1  R6_2.5.0         
  Rcpp_1.0.7        rlang_0.4.11      rmarkdown_2.9.2   servr_0.22       
  stats_4.1.0       stringi_1.6.2     stringr_1.4.0     tinytex_0.32     
  tools_4.1.0       utils_4.1.0       xfun_0.24         yaml_2.2.1       

Hugo version: 0.85.0
```
Any help will be appreciated. Thank you.

**Comment by cderv** [comment] 2021-07-13 14:44
Thank for your report. 

This is a duplicate of https://github.com/rstudio/blogdown/issues/638 where we are looking into it.

**Comment by cderv** [comment] 2021-07-13 14:44
Duplicate of #638

**Closed as completed by cderv** 2021-07-13 14:44 UTC
